name = "VirtualEcologicalLaboratory"
uuid = "de702101-8788-42bc-9508-b66cc959d566"
authors = ["michael catchen <michael.catchen@colorado.edu>"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
